### ISSUE TITLE
Using a title causes the count to not show

### ISSUE THREAD

**Issue by mbarkmeier** [JetBrains/youtrack-streamdeck-plugin#1]
Using the title to display the name and count makes it so if a Title is specified then only the title is displayed. This caused me to think it wasn't pulling the ticket count because I put the title in before anything else

**Comment by annikovk** [comment]
Thank you for the request! 
I disabled title editing in the manifest (see d67212b). The updated version will be in the marketplace after moderation 
![image](https://user-images.githubusercontent.com/12910542/232710260-14b5b8fb-faaa-4a3c-bd72-5b1be6a08142.png)


Unfortunately, it is impossible to hide the title input in the settings or post-process the value somehow. Here are the related threads: 

https://www.reddit.com/r/StreamDeckSDK/comments/oxww9z/hide_title_in_property_inspector/
https://www.reddit.com/r/StreamDeckSDK/comments/leitz8/how_to_disable_title_lineedit/

**Comment by annikovk** [comment]
Updated plugin package is available on the [releases](https://github.com/JetBrains/youtrack-streamdeck-plugin/releases/latest) page
